index = 20
name = "Lasagnesuppe"
cook_time = "35 min"
prep_time = "10 min"
portions = 6
store_time = "5 Tage"
energy = "424.97 kcal"
kind = 1
instructions = [
    "Koche 1 Liter Gemüsebrühe nach Anleitung in einem großen Topf.",
    "Schneide die Zwiebel und hacke den Knoblauch. Gib beides zusammen mit dem Olivenöl in einen großen Suppentopf. Sauté bei mittlerer Hitze, bis die Zwiebeln weich und durchsichtig sind (etwa 3-5 Minuten).",
    "Während die Zwiebeln und der Knoblauch braten, schäle und schneide die Karotten. Schneide die Zucchini und dann die Scheiben in Viertelrunden. Gib die Karotten und Zucchini in den Topf und brate sie etwa 2 Minuten weiter, bis die Zucchini etwas weich werden.",
    "Füge die gewürfelten Tomaten (mit Saft), Tomatensauce und italienische Gewürzmischung zur Gemüsebrühe in den Suppentopf. Rühre gut um. Setze einen Deckel auf den Topf, erhöhe die Hitze auf mittelhoch und bringe die Suppe zum Kochen.",
    "Während du auf das Kochen wartest, breche die Lasagneblätter in 2,5 cm große Stücke. Sobald die Suppe kocht, gib die zerbrochenen Lasagneblätter dazu und koche sie 10-12 Minuten weiter, bis die Nudeln zart sind.",
    "Während die Pasta in der Suppe kocht, vermenge den Ricotta, die Hälfte des geriebenen Mozzarella, Parmesan, Salz und frisch gemahlenen Pfeffer in einer Schüssel (bewahre den restlichen Mozzarella zum Bestreuen der Suppenschalen auf). Rühre alles gut um, bis die Käse und Gewürze gut vermischt sind.",
    "Sobald die Pasta zart ist, füge den Spinat hinzu und rühre, bis der Spinat gut in die Suppe eingemischt ist.",
    "Zum Servieren gebe ein Viertel der Käsemischung in jede Schüssel und fülle dann die heiße Suppe darüber. Bestreue sie mit einer Prise des restlichen geriebenen Mozzarellas.",
]
subheaders = ["Suppe", "Käsemix"]

[ingredients]
"#Olivenöl" = { amount = 1, unit = " EL", kind = 6, sub = 0 }
"#gelbe Zwiebel" = { amount = 1, unit = "", kind = 0, sub = 0 }
"#Knoblauchzehen" = { amount = 4, unit = "", kind = 0, sub = 0 }
"#Karotten" = { amount = 2, unit = "", kind = 0, sub = 0 }
"#Zucchini" = { amount = 1, unit = "", kind = 0, sub = 0 }
"#gewürfelte Tomaten" = { amount = 1, unit = " Dose", kind = 4, sub = 0 }
"#Tomatensauce" = { amount = 1, unit = " Dose", kind = 4, sub = 0 }
"#Italienische Gewürz-|mischung" = { amount = 1, unit = " EL", kind = 6, sub = 0 }
"Pulver für |#Gemüsebrühe" = { amount = 1000, unit = " ml", kind = 3, sub = 0 }
"#Lasagneblätter" = { amount = 250, unit = "g", kind = 3, sub = 0 }
"#Spinat" = { amount = 100, unit = "g", kind = 0, sub = 0 }

"#Ricotta" = { amount = 400, unit = "g", kind = 2, sub = 1 }
"#Mozzarella" = { amount = 100, unit = "g", kind = 2, sub = 1 }
"#Parmesan" = { amount = 30, unit = "g", kind = 2, sub = 1 }
"#Salz" = { amount = 0.125, unit = " TL", kind = 6, sub = 1 }
"#Pfeffer" = { amount = 1, unit = " Prise", kind = 6, sub = 1 }
