index = 21
name = "Schwein und Erdnuss |Drachennudeln"
cook_time = "50 min"
prep_time = "30 min"
portions = 4
store_time = "3 Tage"
energy = " kcal"
kind = 2
instructions = [
    "Bereite zuerst das Sesamdressing zu, damit sich die Aromen gut vermischen können. Gib das Öl, den Reisessig, die Sojasauce, das geröstete Sesamöl, den braunen Zucker, den frisch geriebenen Ingwer und die Sesamsamen in ein kleines Glas oder eine Schüssel. Schlage die Zutaten zusammen oder verschließe das Glas und schüttle es, um sie zu vermengen. Stelle das Dressing zur Seite, bis es verwendet wird.",
    "Schneide den Brokkoli in mundgerechte Röschen und verteile sie auf einem Backblech. Heize den Ofen auf 200ºC vor. Beträufle den Brokkoli mit 1 EL Öl und einer Prise Salz und vermenge alles gut.",
    "Röste den Brokkoli 8 Minuten im vorgeheizten Ofen. Streue nach 3 Minuten die Mandelscheiben über den Brokkoli und lasse sie für die letzten fünf Minuten mitrösten. Nimm den Brokkoli und die Mandeln aus dem Ofen und lasse sie 5-10 Minuten abkühlen.",
    "Für die Drachensauce, vermische die Chili-Knoblauch-Sauce, die Sojasauce und den braunen Zucker in einer Schüssel.",
    "Gib das Schweinehackfleisch in eine Pfanne und brate es bei mittlerer Hitze, bis es vollständig braun ist. Sobald es braun ist, füge die vorbereitete Drachensauce und die gehackten Erdnüsse hinzu. Lasse das Fleisch mit den Erdnüssen 5 Minuten in der Sauce köcheln, bis die Sauce um die Hälfte reduziert ist.",
    "Während das Schweinefleisch brät, koche Wasser für die Nudeln. Sobald es kocht, gib die Nudeln hinein und koche sie nach Packungsanweisung. Lasse die Nudeln in einem Sieb abtropfen.",
    "Wenn die Sauce reduziert ist und die Nudeln abgetropft sind, gib die Nudeln in die Pfanne und vermenge alles gut, bis die Nudeln gleichmäßig mit der Sauce überzogen sind.",
    "Sobald der Brokkoli fast abgekühlt ist, füge die geschnittenen Frühlingszwiebeln hinzu und vermenge alles. Rühre das einfache Sesam-Dressing noch einmal um oder schüttle es und träufle es dann über das Backblech. Rühre alles gut um, damit alles mit dem Dressing überzogen ist.",
    "Vermische das Schweinefleisch, die Nudeln und den Brokkoli in vorbereiteten Behältern.",
]
subheaders = ["Drachensauce", "Nudeln", "Sesamdressing", "Brokkoli"]

[ingredients]
"#Chili-Knoblauch-Sauce" = { amount = 60, unit = "ml", kind = 6, sub = 0 }
"#Sojasauce" = [
    { amount = 60, unit = "ml", kind = 6, sub = 0 },
    { amount = 40, unit = "ml", kind = 6, sub = 2 },
]
"#brauner Zucker" = [
    { amount = 3, unit = " EL", kind = 6, sub = 0 },
    { amount = 2, unit = " EL", kind = 6, sub = 2 },
]

"#Schweinehackfleisch" = { amount = 250, unit = "g", kind = 1, sub = 1 }
"#Instant Ramen |Nudeln" = { amount = 3, unit = " Blöcke", kind = 3, sub = 1 }
"#Frühlingszwiebeln" = [
    { amount = 3, unit = "", kind = 0, sub = 1 },
    { amount = 4, unit = "", kind = 0, sub = 3 },
]
"#Erdnüsse" = { amount = 30, unit = "g", kind = 3, sub = 1 }

"#Sonnenblumenöl" = [
    { amount = 4, unit = " EL", kind = 6, sub = 2 },
    { amount = 2, unit = " EL", kind = 6, sub = 3 },
]
"#Reisessig" = { amount = 2, unit = " EL", kind = 6, sub = 2 }
"#geröstetes Sesamöl" = { amount = 2, unit = " TL", kind = 6, sub = 2 }
"#geriebener Ingwer" = { amount = 2, unit = " TL", kind = 0, sub = 2 }
"#Sesam" = { amount = 1, unit = " EL", kind = 6, sub = 2 }

"#Brokkoli" = { amount = 1, unit = "kg", kind = 0, sub = 3 }
"#Salz" = { amount = 1, unit = " Prise", kind = 6, sub = 3 }
"#Mandeln" = { amount = 80, unit = "g", kind = 3, sub = 3 }
