index = 4
name = "Kohl und Süßkartoffel|Salat"
cook_time = "30 min"
prep_time = "20 min"
portions = 4
store_time = "5 Tage"
energy = "512 kcal"
kind = 0
instructions = [
    "Den Backofen auf 200 °C vorheizen. Die Süßkartoffeln schälen und in 1,5 cm große Würfel schneiden. Die Süßkartoffelstücke auf ein mit Backpapier ausgelegtes Backblech legen und mit Sonnenblumenöl, Zimt, Kreuzkümmel, geräuchertem Paprikapulver und Salz vermengen. Die Süßkartoffeln gut durchmischen, bis sie gleichmäßig mit Öl und Gewürzen bedeckt sind.",
    "Die Süßkartoffeln etwa 30 Minuten rösten, bis sie zart und an den Rändern gebräunt sind. Nach der Hälfte der Zeit einmal umrühren.",
    "Während die Süßkartoffeln rösten, den Rest des Salats vorbereiten. Mit dem Dressing beginnen. Tahin, Zitronensaft, Ahornsirup, Knoblauchpulver, Cayennepfeffer, Salz und 60ml Wasser in einen Mixer oder eine Schüssel geben. Alles mixen oder mit einem Schneebesen verrühren, bis eine glatte, emulgierte Mischung entsteht. Das Dressing beiseitestellen.",
    "Kohl in dünne Streifen schneiden und unter kaltem Wasser gründlich waschen. Den geschnittenen Kohl auf vier Schalen oder Behälter verteilen.",
    "Den Apfel vierteln und das Kerngehäuse entfernen. Jedes Viertel in dünne Scheiben schneiden. Die Apfelscheiben auf die Behälter verteilen.",
    "Jeweils 1 EL Kürbiskerne, gehackte Pekannüsse und getrocknete Cranberries zu jedem Behälter hinzufügen. Sobald die Süßkartoffeln fertig geröstet sind, diese etwa 5 Minuten abkühlen lassen, dann gleichmäßig auf die Behälter verteilen. Das Dressing auf vier kleine Behälter aufteilen. Den Salat sofort genießen oder bis zu fünf Tage im Kühlschrank aufbewahren (Dressing separat aufbewahren).",
]
subheaders = ["Geröstete Süßkartoffel", "Ahorn Tahin Dressing", "Salat"]

[ingredients]
# Roasted Sweet Potatoes
"#Süßkartoffel" = { amount = 900, unit = "g", kind = 0, sub = 0 }
"#Sonnenblumenöl" = { amount = 1, unit = " EL", kind = 6, sub = 0 }
"#Zimt" = { amount = 0.25, unit = " TL", kind = 6, sub = 0 }
"#gemahlener Kreuzkümmel" = { amount = 0.5, unit = " TL", kind = 6, sub = 0 }
"#geräuchertes Paprikapulver" = { amount = 0.25, unit = " TL", kind = 6, sub = 0 }
"#Salz" = [
    { amount = 0.25, unit = " TL", kind = 6, sub = 0 },
    { amount = 0.25, unit = " TL", kind = 6, sub = 1 },
]

# Maple Tahini Dressing
"#Tahin" = { amount = 60, unit = "ml", kind = 6, sub = 1 }
"#Zitronensaft" = { amount = 2, unit = " EL", kind = 6, sub = 1 }
"#Ahornsirup" = { amount = 2, unit = " EL", kind = 6, sub = 1 }
"#Knoblauchpulver" = { amount = 0.25, unit = " TL", kind = 6, sub = 1 }
"#Cayennepfeffer" = { amount = 0.125, unit = " TL", kind = 6, sub = 1 }

# Salad
"#Kohl" = { amount = 300, unit = "g", kind = 0, sub = 2 }
"#großer Apfel" = { amount = 1, unit = "", kind = 0, sub = 2 }
"#Kürbiskerne" = { amount = 250, unit = "g", kind = 3, sub = 2 }
"#gehackte Pekan-|nüsse" = { amount = 250, unit = "g", kind = 3, sub = 2 }
"#getrocknete |Cranberries" = { amount = 250, unit = "g", kind = 3, sub = 2 }
