index = 5
name = "Gerösteter Gemüsesalat"
cook_time = "60 min"
prep_time = "20 min"
portions = 4
store_time = "4 Tage"
energy = "395.3 kcal"
kind = 0
instructions = [
    "Zuerst das Dressing zubereiten. Knoblauchpulver, Zwiebelpulver, Dill, Petersilie, Salz, Pfeffer, Tahin, Zitronensaft und 60ml Wasser in einer kleinen Schüssel vermengen. Mit einem Schneebesen oder Löffel glatt rühren. Das Dressing in den Kühlschrank stellen, während der Rest des Salats vorbereitet wird.",
    "Das Quinoa in einem feinmaschigen Sieb gut abspülen. Das gespülte Quinoa in einen kleinen Topf geben und 1,75 Tassen Wasser hinzufügen. Einen Deckel auf den Topf setzen, die Hitze auf hoch stellen und das Wasser zum Kochen bringen. Sobald es kocht, die Hitze auf niedrig stellen und das Quinoa 15 Minuten lang köcheln lassen.",
    "Nach 15 Minuten die Hitze ausschalten und das Quinoa mit geschlossenem Deckel fünf Minuten ruhen lassen. Das gekochte Quinoa in eine Auflaufform geben und gleichmäßig verteilen, um die Oberfläche zu vergrößern. Die Form mit dem Quinoa in den Kühlschrank stellen.",
    "Den Backofen auf 200 °C vorheizen. Die Kirschtomaten auf ein großes Backblech legen. Die Zwiebel in 0,5 cm breite Streifen schneiden. Die Zucchini und den gelben Kürbis in 0,5 cm breite Halbkreise schneiden. Die Champignons halbieren. Das Gemüse auf dem Backblech vermengen. Wenn zu viel Gemüse vorhanden ist, um es in einer Schicht auf dem Backblech zu verteilen, es auf zwei Backbleche aufteilen.",
    "Das Olivenöl, den Oregano, das Knoblauchpulver und das Salz zum Gemüse hinzufügen. Das Gemüse mit den Händen gut durchmischen, bis es gleichmäßig mit Öl und Gewürzen bedeckt ist.",
    "Das Gemüse im vorgeheizten Ofen bei 200 °C rösten, dabei alle 15 Minuten umrühren, bis es an den Rändern gebräunt ist. Das geröstete Gemüse etwa 10 Minuten bei Raumtemperatur abkühlen lassen.",
    "4 Behälter vorbeireiten. Jeweils eine gehäufte Tasse Spinat in jeden Behälter geben. 1/2 Tasse des gekochten und abgekühlten Quinoas auf den Spinat legen. Das geröstete Gemüse gleichmäßig auf die vier Behältnisse verteilen und je 2 EL Hummus hinzufügen.",
    "Das Dressing auf vier kleine Behälter aufteilen. Die Salate und das Dressing bis zu 4 Tage im Kühlschrank aufbewahren.",
]
subheaders = ["Dressing", "Quinoa", "Salat"]

[ingredients]
# Lemon Dill Tahini Dressing
"#Knoblauchpulver" = [
    { amount = 0.25, unit = " TL", kind = 6, sub = 0 },
    { amount = 0.25, unit = " TL", kind = 6, sub = 1 },
]
"#Zwiebelpulver" = { amount = 0.25, unit = " TL", kind = 6, sub = 0 }
"#getrockneter Dill" = { amount = 0.5, unit = " TL", kind = 6, sub = 0 }
"#getrocknete Petersilie" = { amount = 0.5, unit = " TL", kind = 6, sub = 0 }
"#Salz" = [
    { amount = 0.25, unit = " TL", kind = 6, sub = 0 },
    { amount = 0.25, unit = " TL", kind = 6, sub = 1 },
]
"#Pfeffer" = { amount = 1, unit = " Prise", kind = 6, sub = 0 }
"#Tahin" = { amount = 60, unit = "ml", kind = 6, sub = 0 }
"#Zitronensaft" = { amount = 3, unit = " EL", kind = 6, sub = 0 }

# Quinoa
"#Quinoa" = { amount = 1, unit = " Tasse", kind = 3, sub = 1 }
"#Kirschtomaten" = { amount = 400, unit = "g", kind = 0, sub = 1 }
"#Champignons" = { amount = 250, unit = "g", kind = 0, sub = 1 }
"#Zucchini" = { amount = 1, unit = "", kind = 0, sub = 1 }
"#gelber Kürbis" = { amount = 1, unit = "", kind = 0, sub = 1 }
"#rote Zwiebel" = { amount = 1, unit = "", kind = 0, sub = 1 }
"#Olivenöl" = { amount = 2, unit = " EL", kind = 6, sub = 1 }
"#getrockneter Oregano" = { amount = 1, unit = " TL", kind = 6, sub = 1 }
"#Spinat" = { amount = 150, unit = "g", kind = 0, sub = 1 }
"#Hummus" = { amount = 250, unit = "g", kind = 7, sub = 1 }
